campaignwarehouse:
  target: dev

  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: postgres
      password: password
      dbname: local
      schema: public
      threads: 4
      keepalives_idle: 0
