version: 2

models:
  - name: int_ads_google
    columns:
      - name: conversions
        tests:
          - not_null
      - name: spend
        tests:
          - not_null

  - name: int_ads_facebook
    columns:
      - name: conversions
        tests:
          - not_null
      - name: spend
        tests:
          - not_null

  - name: int_crm_revenue
    columns:
      - name: revenue
        tests:
          - not_null
          
